# Generated by Django 4.1.6 on 2023-02-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="msg",
        ),
        migrations.AddField(
            model_name="message",
            name="value",
            field=models.CharField(default="hi", max_length=1000000),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
